### ISSUE TITLE
error with call freq

### ISSUE THREAD

**Issue by sengelen** [PengNi/deepsignal3#4]
Dear all,

I wanted to test deepsignal3 on a small sample of an ONT run (360000 reads in pod5 format) basecalled with dorado 0.7.1. So I ran the call_mods command on a100 GPU nodes ran with success :
```
 deepsignal3 --pod5 call_mods --input_path pod5sample/ --bam sample.bam --model_path human_r1041_5khz_CG_epoch5.ckpt --result_file sample.CG.call_mods.tsv --nproc 64 --nproc_gpu 4 --seq_len 21 --signal_len 15 -b 8192
```
I obtained a correct call_mods file with 25559702 lines and some methylation detected on input reads :

```
ptg000141l      43099   -       .       17de2869-a5d2-4eb1-800f-9814c8412505    .       0.890247        0.109753        0       TGCGT
ptg000141l      43000   -       .       17de2869-a5d2-4eb1-800f-9814c8412505    .       0.996604        0.003396        0       AACGC
ptg000141l      42972   -       .       17de2869-a5d2-4eb1-800f-9814c8412505    .       0.9838  0.0162  0       ACCGG
ptg000141l      42819   -       .       17de2869-a5d2-4eb1-800f-9814c8412505    .       0.998306        0.001694        0       CACGC
ptg000141l      42814   -       .       17de2869-a5d2-4eb1-800f-9814c8412505    .       0.995444        0.004556        0       CACGG
ptg000141l      42788   -       .       17de2869-a5d2-4eb1-800f-9814c8412505    .       0.990514        0.009486        0       AGCGC
ptg000141l      42774   -       .       17de2869-a5d2-4eb1-800f-9814c8412505    .       0.992809        0.007191        0       CTCGG
ptg000141l      42668   -       .       17de2869-a5d2-4eb1-800f-9814c8412505    .       0.964888        0.035112        0       GTCGA
ptg000141l      42630   -       .       17de2869-a5d2-4eb1-800f-9814c8412505    .       0.986044        0.013956        0       ACCGA
ptg000141l      42462   -       .       17de2869-a5d2-4eb1-800f-9814c8412505    .       0.998218        0.001782        0       CTCGA
...
ptg000141l      39223   -       .       17de2869-a5d2-4eb1-800f-9814c8412505    .       0.993512        0.006488        0       CTCGG
ptg000141l      39094   -       .       17de2869-a5d2-4eb1-800f-9814c8412505    .       0.448298        0.551702        1       CTCGA
ptg000141l      39080   -       .       17de2869-a5d2-4eb1-800f-9814c8412505    .       0.996746        0.003254        0       ATCGA
ptg000141l      39055   -       .       17de2869-a5d2-4eb1-800f-9814c8412505    .       0.985257        0.014743        0       AGCGC
```
But after that I had an arror with this call_freq command :
```
deepsignal3 call_freq --input_path sample.CG.call_mods.tsv --result_file sample.CG.frequency.tsv
```
Here is the error :
```
Traceback (most recent call last):
  File "/usr/local/bin/deepsignal3", line 33, in <module>
    sys.exit(load_entry_point('deepsignal3==0.1.1', 'console_scripts', 'deepsignal3')())
  File "/usr/local/lib/python3.10/dist-packages/deepsignal3-0.1.1-py3.10.egg/deepsignal3/deepsignal3.py", line 1240, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/deepsignal3-0.1.1-py3.10.egg/deepsignal3/deepsignal3.py", line 50, in main_call_freq
    call_mods_frequency_to_file(args)
  File "/usr/local/lib/python3.10/dist-packages/deepsignal3-0.1.1-py3.10.egg/deepsignal3/call_mods_freq.py", line 141, in call_mods_frequency_to_file
    write_sitekey2stats(sites_stats, result_file, issort, isbed)
  File "/usr/local/lib/python3.10/dist-packages/deepsignal3-0.1.1-py3.10.egg/deepsignal3/call_mods_freq.py", line 93, in write_sitekey2stats
    "%s\t%d\t%s\t%d\t%.3f\t%.3f\t%d\t%d\t%d\t%.4f\t%s\n"
TypeError: %d format: a real number is required, not str
```
Any idea ?

Thank you
Best
Stefan

**Comment by xyfltq** [comment]
Hi @sengelen , thanks very much for using our tool. This bug has been fixed. You can reinstall the tool or add the -- bed parameter.

**Comment by sengelen** [comment]
Hi,

Thank you for your answer.
Indeed I saw that it works with the --bed parameter but I prefer the tsv output. I already used the latest version so I think this is not fixed. Do you think you could fixed it ? 

Thank you 
Best 
Stefan

**Comment by xyfltq** [comment]
Hi @sengelen , Can I take a look at the latest error message？ Have you installed the program using python setup.py install after downloading the latest code?

**Comment by sengelen** [comment]
Hi, sorry I didn't see your last debug, so I relaunched deepsignal3 with your last update and it's works without the --bed parameter !!!

Thank you 
best
Stefan
